apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: dc-metro-map-m4e1
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dc-metro-map-m4e1
    app.kubernetes.io/part-of: appstudio
  name: dc-metro-map-m4e1
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: dc-metro-map-m4e1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: dc-metro-map-m4e1
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/ex-registry-qwwa-tenant/appstudio/dc-metro-map-m4e1@sha256:41df8c5a3d602fa0e5be55fbd27157fbf807d687322c1438b9dd89d607cf60f4
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        - containerPort: 8081
        resources:
          limits:
            cpu: 50m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 25Mi
status: {}
